
-- INCISO B

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- CREAR BASE DE DATOS
DROP SCHEMA IF EXISTS `inciso_b`;
CREATE SCHEMA IF NOT EXISTS `inciso_b` DEFAULT CHARACTER SET utf8;
USE `inciso_b`;

-- Tabla EMPRESA
CREATE TABLE IF NOT EXISTS `EMPRESA` (
  `idEm` INT NOT NULL,
  `nomEm` VARCHAR(90) NOT NULL,
  `telEm` VARCHAR(12) NOT NULL,
  `colEm` VARCHAR(45) NOT NULL,
  `CalleEm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEm`)
) ENGINE = InnoDB;

-- Tabla PRESUPUESTO
CREATE TABLE IF NOT EXISTS `PRESUPUESTO` (
  `idPre` INT NOT NULL,
  `cantidad` INT NOT NULL,
  `fecha` DATE NOT NULL,
  PRIMARY KEY (`idPre`)
) ENGINE = InnoDB;

-- Tabla SERVICIO_DE_ACTO
CREATE TABLE IF NOT EXISTS `SERVICIO_DE_ACTO` (
  `idCam` INT NOT NULL,
  `cod` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `lugar` VARCHAR(50) NOT NULL,
  `idPre2` INT NOT NULL,
  PRIMARY KEY (`idCam`, `cod`),
  INDEX `idPre_idx` (`idPre2`),
  CONSTRAINT `idPre`
    FOREIGN KEY (`idPre2`)
    REFERENCES `PRESUPUESTO` (`idPre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla SOLICITA
CREATE TABLE IF NOT EXISTS `SOLICITA` (
  `idEm1` INT NOT NULL,
  `idPre1` INT NOT NULL,
  `hora` TIME NOT NULL,
  `fecha` DATE NOT NULL,
  `presupuesto` FLOAT NOT NULL,
  PRIMARY KEY (`idEm1`, `idPre1`),
  INDEX `idEm1_idx` (`idEm1`),
  INDEX `idPre1_idx` (`idPre1`),
  CONSTRAINT `idEm1`
    FOREIGN KEY (`idEm1`)
    REFERENCES `EMPRESA` (`idEm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPre1`
    FOREIGN KEY (`idPre1`)
    REFERENCES `PRESUPUESTO` (`idPre`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla CONTRATAR
CREATE TABLE IF NOT EXISTS `CONTRATAR` (
  `idEm2` INT NOT NULL,
  `idCam1` INT NOT NULL,
  `cod1` INT NOT NULL,
  PRIMARY KEY (`idEm2`, `idCam1`, `cod1`),
  INDEX `idCam1_idx` (`idCam1`),
  INDEX `idEm2_idx` (`idEm2`),
  CONSTRAINT `idEm2`
    FOREIGN KEY (`idEm2`)
    REFERENCES `EMPRESA` (`idEm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_contratar_servicio`
    FOREIGN KEY (`idCam1`, `cod1`)
    REFERENCES `SERVICIO_DE_ACTO` (`idCam`, `cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla PLATO
CREATE TABLE IF NOT EXISTS `PLATO` (
  `idPla` INT NOT NULL,
  `precio` FLOAT NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `nomPla` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPla`)
) ENGINE = InnoDB;

-- Tabla SIRVEN
CREATE TABLE IF NOT EXISTS `SIRVEN` (
  `idCam3` INT NOT NULL,
  `cod3` INT NOT NULL,
  `idPla1` INT NOT NULL,
  PRIMARY KEY (`idCam3`, `cod3`, `idPla1`),
  INDEX `idCam3_idx` (`idCam3`),
  INDEX `idPla1_idx` (`idPla1`),
  CONSTRAINT `fk_sirven_servicio`
    FOREIGN KEY (`idCam3`, `cod3`)
    REFERENCES `SERVICIO_DE_ACTO` (`idCam`, `cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_sirven_plato`
    FOREIGN KEY (`idPla1`)
    REFERENCES `PLATO` (`idPla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla TIPO_COMIDA
CREATE TABLE IF NOT EXISTS `TIPO_COMIDA` (
  `idTipo` INT NOT NULL,
  `tipo1` VARCHAR(45) NOT NULL,
  `tipo2` VARCHAR(45) NOT NULL,
  `nomTipo` VARCHAR(45) NOT NULL,
  `idPla2` INT NOT NULL,
  PRIMARY KEY (`idTipo`),
  INDEX `idPla2_idx` (`idPla2`),
  CONSTRAINT `idPla2`
    FOREIGN KEY (`idPla2`)
    REFERENCES `PLATO` (`idPla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla PRODUCTO
CREATE TABLE IF NOT EXISTS `PRODUCTO` (
  `codProd` INT NOT NULL,
  `nomProd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codProd`)
) ENGINE = InnoDB;

-- Tabla COMPUESTO
CREATE TABLE IF NOT EXISTS `COMPUESTO` (
  `idPlato3` INT NOT NULL,
  `codProd1` INT NOT NULL,
  PRIMARY KEY (`idPlato3`, `codProd1`),
  INDEX `idPla3_idx` (`idPlato3`),
  INDEX `codProd1_idx` (`codProd1`),
  CONSTRAINT `idPla3`
    FOREIGN KEY (`idPlato3`)
    REFERENCES `PLATO` (`idPla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `codProd1`
    FOREIGN KEY (`codProd1`)
    REFERENCES `PRODUCTO` (`codProd`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla EMPLEADO
CREATE TABLE IF NOT EXISTS `EMPLEADO` (
  `codEm` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codEm`)
) ENGINE = InnoDB;

-- Tabla COCINERO
CREATE TABLE IF NOT EXISTS `COCINERO` (
  `idCo` INT NOT NULL,
  `idPla4` INT NOT NULL,
  `codEm1` INT NOT NULL,
  PRIMARY KEY (`idCo`),
  INDEX `codEm1_idx` (`codEm1`),
  INDEX `idPla4_idx` (`idPla4`),
  CONSTRAINT `codEm1`
    FOREIGN KEY (`codEm1`)
    REFERENCES `EMPLEADO` (`codEm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `idPla4`
    FOREIGN KEY (`idPla4`)
    REFERENCES `PLATO` (`idPla`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla CAMARERO
CREATE TABLE IF NOT EXISTS `CAMARERO` (
  `idCama` INT NOT NULL,
  `codEm2` INT NOT NULL,
  PRIMARY KEY (`idCama`),
  INDEX `codEm2_idx` (`codEm2`),
  CONSTRAINT `codEm2`
    FOREIGN KEY (`codEm2`)
    REFERENCES `EMPLEADO` (`codEm`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Tabla ATENDIDO
CREATE TABLE IF NOT EXISTS `ATENDIDO` (
  `fecha` DATE NOT NULL,
  `idCama1` INT NOT NULL,
  `idCam4` INT NOT NULL,
  `cod4` INT NOT NULL,
  PRIMARY KEY (`fecha`, `idCama1`, `idCam4`, `cod4`),
  INDEX `idCama1_idx` (`idCama1`),
  INDEX `idCam4_idx` (`idCam4`),
  CONSTRAINT `fk_atendido_camarero`
    FOREIGN KEY (`idCama1`)
    REFERENCES `CAMARERO` (`idCama`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `fk_atendido_servicio`
    FOREIGN KEY (`idCam4`, `cod4`)
    REFERENCES `SERVICIO_DE_ACTO` (`idCam`, `cod`)
    ON DELETE CASCADE
    ON UPDATE CASCADE
) ENGINE = InnoDB;

-- Restaurar valores
SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
