
-- INCISO A 

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS;
SET UNIQUE_CHECKS = 0;

SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS;
SET FOREIGN_KEY_CHECKS = 0;

SET @OLD_SQL_MODE = @@SQL_MODE;
SET SQL_MODE = 'ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- Reinicio del esquema
DROP SCHEMA IF EXISTS `inciso_a`;
CREATE SCHEMA IF NOT EXISTS `inciso_a` DEFAULT CHARACTER SET utf8;
USE `inciso_a`;


-- TABLA EMPRESA
CREATE TABLE IF NOT EXISTS `EMPRESA` (
  `idEm` INT NOT NULL,
  `nomEm` VARCHAR(90) NOT NULL,
  `telEm` VARCHAR(12) NOT NULL,
  `CalleEm` VARCHAR(45) NOT NULL,
  `colEm` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idEm`)
) ENGINE=InnoDB;

-- TABLA PRESUPUESTO
CREATE TABLE IF NOT EXISTS `PRESUPUESTO` (
  `idPre` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`idPre`)
) ENGINE=InnoDB;

-- TABLA SERVICIO_DE_ACTO
CREATE TABLE IF NOT EXISTS `SERVICIO_DE_ACTO` (
  `idCam` INT NOT NULL,
  `cod` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `lugar` VARCHAR(50) NOT NULL,
  `idPre2` INT NOT NULL,
  PRIMARY KEY (`idCam`, `cod`),
  INDEX `idx_idPre2` (`idPre2`),
  CONSTRAINT `idPre`
    FOREIGN KEY (`idPre2`) REFERENCES `PRESUPUESTO` (`idPre`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA SOLICITA
CREATE TABLE IF NOT EXISTS `SOLICITA` (
  `idEm1` INT NOT NULL,
  `idPre1` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `presupuesto` FLOAT NOT NULL,
  PRIMARY KEY (`idEm1`, `idPre1`),
  INDEX `idx_idEm1` (`idEm1`),
  INDEX `idx_idPre1` (`idPre1`),
  CONSTRAINT `idEm1`
    FOREIGN KEY (`idEm1`) REFERENCES `EMPRESA` (`idEm`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `idPre1`
    FOREIGN KEY (`idPre1`) REFERENCES `PRESUPUESTO` (`idPre`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA CONTRATAR
CREATE TABLE IF NOT EXISTS `CONTRATAR` (
  `idEm2` INT NOT NULL,
  `cod1` INT NOT NULL,
  `idCam1` INT NOT NULL,
  PRIMARY KEY (`idEm2`, `idCam1`, `cod1`),
  INDEX `idx_idEm2` (`idEm2`),
  INDEX `idx_idCam1` (`idCam1`),
  CONSTRAINT `idEm2`
    FOREIGN KEY (`idEm2`) REFERENCES `EMPRESA` (`idEm`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_contratar_servicio`
    FOREIGN KEY (`idCam1`, `cod1`) REFERENCES `SERVICIO_DE_ACTO` (`idCam`, `cod`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA PLATO
CREATE TABLE IF NOT EXISTS `PLATO` (
  `idPla` INT NOT NULL,
  `nomPla` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `precio` FLOAT NOT NULL,
  PRIMARY KEY (`idPla`)
) ENGINE=InnoDB;

-- TABLA SIRVEN
CREATE TABLE IF NOT EXISTS `SIRVEN` (
  `idPla1` INT NOT NULL,
  `idCam3` INT NOT NULL,
  `cod3` INT NOT NULL,
  PRIMARY KEY (`idCam3`, `cod3`, `idPla1`),
  INDEX `idx_idCam3` (`idCam3`),
  INDEX `idx_idPla1` (`idPla1`),
  CONSTRAINT `fk_sirven_servicio`
    FOREIGN KEY (`idCam3`, `cod3`) REFERENCES `SERVICIO_DE_ACTO` (`idCam`, `cod`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_sirven_plato`
    FOREIGN KEY (`idPla1`) REFERENCES `PLATO` (`idPla`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA TIPO_COMIDA
CREATE TABLE IF NOT EXISTS `TIPO_COMIDA` (
  `idTipo` INT NOT NULL,
  `tipo1` VARCHAR(45) NOT NULL,
  `tipo2` VARCHAR(45) NOT NULL,
  `nomTipo` VARCHAR(45) NOT NULL,
  `idPla2` INT NOT NULL,
  PRIMARY KEY (`idTipo`),
  INDEX `idx_idPla2` (`idPla2`),
  CONSTRAINT `idPla2`
    FOREIGN KEY (`idPla2`) REFERENCES `PLATO` (`idPla`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA PRODUCTO
CREATE TABLE IF NOT EXISTS `PRODUCTO` (
  `codProd` INT NOT NULL,
  `nomProd` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`codProd`)
) ENGINE=InnoDB;

-- TABLA COMPUESTO
CREATE TABLE IF NOT EXISTS `COMPUESTO` (
  `idPlato3` INT NOT NULL,
  `codProd1` INT NOT NULL,
  PRIMARY KEY (`idPlato3`, `codProd1`),
  INDEX `idx_idPlato3` (`idPlato3`),
  INDEX `idx_codProd1` (`codProd1`),
  CONSTRAINT `idPla3`
    FOREIGN KEY (`idPlato3`) REFERENCES `PLATO` (`idPla`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `codProd1`
    FOREIGN KEY (`codProd1`) REFERENCES `PRODUCTO` (`codProd`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA EMPLEADO
CREATE TABLE IF NOT EXISTS `EMPLEADO` (
  `codEm` INT NOT NULL,
  `nombre` VARCHAR(25) NOT NULL,
  `apellido` VARCHAR(50) NOT NULL,
  `tipo_empleado` ENUM('CAMARERO','COCINERO') NOT NULL,
  `idCama` INT,
  `idPla4` INT,
  `idCo` INT,
  PRIMARY KEY (`codEm`),
  UNIQUE (`idCama`),
  INDEX `idx_idPla4` (`idPla4`),
  CONSTRAINT `fk_empleado_plato`
    FOREIGN KEY (`idPla4`) REFERENCES `PLATO` (`idPla`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- TABLA ATENDIDO
CREATE TABLE IF NOT EXISTS `ATENDIDO` (
  `fecha` DATE NOT NULL,
  `idCam4` INT NOT NULL,
  `cod4` INT NOT NULL,
  `codEm` INT NOT NULL,
  PRIMARY KEY (`fecha`, `codEm`, `idCam4`, `cod4`),
  INDEX `idx_codEm` (`codEm`),
  INDEX `idx_idCam4` (`idCam4`),
  CONSTRAINT `fk_atendido_empleado`
    FOREIGN KEY (`codEm`) REFERENCES `EMPLEADO` (`codEm`)
    ON UPDATE CASCADE ON DELETE CASCADE,
  CONSTRAINT `fk_atendido_servicio`
    FOREIGN KEY (`idCam4`, `cod4`) REFERENCES `SERVICIO_DE_ACTO` (`idCam`, `cod`)
    ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB;

-- RESTAURAR VALORES ORIGINALES
SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
